services:
  p4d:
    image: n3m3515/docker-p4d:latest
    container_name: linux_p4d
    privileged: true
    environment:
      - DB_HOST=p4d_db
      - DB_PORT=3306
      - DB_USER=p4_user
      - DB_PASS=p4_pass
      - DB_NAME=p4_db
      - AG_HISTORY=0
      - AG_INTERVAL=15
      - SMTP_MAIL_FROM=user@web.de
      - SMTP_SERVER=smtp.web.de
      - SMTP_Port=587
      - SMTP_TLS=on
      - SMTP_AUTH=on
      - SMTP_USERNAME=user
      - SMTP_PASSWORD=password
      - TZ=Europe/Berlin
    ports:
      - 1111:1111
      - 1883:1883
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /linux_p4d/scripts:/etc/p4d/scripts.d/user/
      - /linux_p4d/userimages:/var/lib/p4d/img/user/
    restart: unless-stopped
    depends_on:
      - p4d_db
  p4d_db:
    image: lscr.io/linuxserver/mariadb
    container_name: p4d_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=p4_pass
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=p4_db
      - MYSQL_USER=p4_user
      - MYSQL_PASSWORD=p4_pass
    volumes:
      - /linux_p4d/mariadb:/config
    restart: unless-stopped
